openlist:
  url: "http://192.168.123.7:5255"
  username: "admin"
  password: "admin"
  timeout: 30
  retry_max: 3

scanner:
  workers: 32
  queue_size: 10000

database:
  path: "data/media.db"

tmdb:
  api_key: ""
  # 代理地址
  base_url: ""
  image_base_url: ""
  cache_ttl: 86400
  rate_limit: 40

log:
  level: "info"
  output: "stdout"

storage:
  local_paths:
    - "/xunlei"
  quark_paths:
    - "/夸克网盘2/来自：分享/高评分电视剧"
    - "/夸克网盘2/来自：分享/电影"
    - "/夸克网盘2/来自：分享/电视剧"
  tianyi_paths:
    - "/天翼云盘"
